### ISSUE TITLE
[REFACTOR] Check for Array Undefined

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#102]
I20160711-11:45:24.677(-4)? Exception from sub user-courses id LDPG7KAyHX6of4i9M TypeError: Cannot call method 'concat' of undefined
I20160711-11:45:24.759(-4)?     at Subscription.<anonymous> (collections/courses.ts:61:58)
I20160711-11:45:24.760(-4)?     at Computation.<anonymous> (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:313:1)
I20160711-11:45:24.760(-4)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160711-11:45:24.760(-4)?     at packages/meteor/dynamics_nodejs.js:123:1
I20160711-11:45:24.760(-4)?     at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:446:1
I20160711-11:45:24.760(-4)?     at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:424:1
I20160711-11:45:24.760(-4)?     at Function.FiberUtils.synchronize (packages/peerlibrary_fiber-utils/packages/peerlibrary_fiber-utils.js:163:1)
I20160711-11:45:24.761(-4)?     at Computation.Tracker.Computation.Computation._runInside (packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:413:1)
I20160711-11:45:24.761(-4)?     at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:438:1
I20160711-11:45:24.761(-4)?     at Function.FiberUtils.synchronize (packages/peerlibrary_fiber-utils/packages/peerlibrary_fiber-utils.js:163:1)

**Comment by DerekTBrown** [comment]
Fixed in https://github.com/learnlinux/tuxlab-app/commit/0bf9635dda5429895ca7174bc702a5e42ce8bba2
