### ISSUE TITLE
[BUG] ID Validation

### ISSUE THREAD

**Issue by sandershihacker** [learnlinux/tuxlab-app#116]

**Comment by DerekTBrown** [comment]
These tests are already included and fail for your ID Verifier.  Here is the output:
```
 Error: courseSchema.addInvalidKeys is not a function
    at /home/derekbro/Projects/tuxlab-app/node_modules/gagarin/lib/meteor/methods.js:105:17            
    at DDPClient._message (/home/derekbro/Projects/tuxlab-app/node_modules/ddp/lib/ddp-client.js:144:7)
    at .<anonymous> (/home/derekbro/Projects/tuxlab-app/node_modules/ddp/lib/ddp-client.js:84:10)      
    at emitOne (events.js:96:13)                                                                       
    at emit (events.js:188:7)                                                                          
    at EventTarget.dispatchEvent (/home/derekbro/Projects/tuxlab-app/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)                                                                
    at instance._receiveMessage (/home/derekbro/Projects/tuxlab-app/node_modules/faye-websocket/lib/faye/websocket/api.js:123:10)                                                                             
    at .<anonymous> (/home/derekbro/Projects/tuxlab-app/node_modules/faye-websocket/lib/faye/websocket/api.js:41:49)                                                                                          
    at emitOne (events.js:101:20)                                                                      
    at emit (events.js:188:7)                                                                          
    at .<anonymous> (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)                                                                                    
    at pipe (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)                                                                                                
    at Pipeline._loop (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)                                                                                       
    at Pipeline.processIncomingMessage (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)                                                                      
    at instance.processIncomingMessage (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)                                                              
    at instance._emitMessage (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)                                                                           
    at instance._emitFrame (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)                                                                             
    at instance.parse (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:141:18)                                                                                  
    at instance.parse (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/client.js:62:58)                                                                                 
    at IO.write (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/streams.js:80:16)                                                                                             
    at Socket.ondata (_stream_readable.js:556:20)                                                      
    at emitOne (events.js:96:13)                                                                       
    at Socket.emit (events.js:188:7)                                                                   
    at readableAddChunk (_stream_readable.js:177:18)                                                   
    at Socket.Readable.push (_stream_readable.js:135:10)                                               
    at TCP.onread (net.js:542:20)                        

```

**Comment by DerekTBrown** [comment]
```
t /home/derekbro/Projects/tuxlab-app/node_modules/gagarin/lib/meteor/methods.js:105:17            
    at DDPClient._message (/home/derekbro/Projects/tuxlab-app/node_modules/ddp/lib/ddp-client.js:144:7)
    at .<anonymous> (/home/derekbro/Projects/tuxlab-app/node_modules/ddp/lib/ddp-client.js:84:10)      
    at emitOne (events.js:96:13)                                                                       
    at emit (events.js:188:7)                                                                          
    at EventTarget.dispatchEvent (/home/derekbro/Projects/tuxlab-app/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)                                                                
    at instance._receiveMessage (/home/derekbro/Projects/tuxlab-app/node_modules/faye-websocket/lib/faye/websocket/api.js:123:10)                                                                             
    at .<anonymous> (/home/derekbro/Projects/tuxlab-app/node_modules/faye-websocket/lib/faye/websocket/api.js:41:49)                                                                                          
    at emitOne (events.js:101:20)                                                                      
    at emit (events.js:188:7)                                                                          
    at .<anonymous> (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)                                                                                    
    at pipe (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)                                                                                                
    at Pipeline._loop (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)                                                                                       
    at Pipeline.processIncomingMessage (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)                                                                      
    at instance.processIncomingMessage (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)                                                              
    at instance._emitMessage (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)                                                                           
    at instance._emitFrame (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)                                                                             
    at instance.parse (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:141:18)                                                                                  
    at instance.parse (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/client.js:62:58)                                                                                 
    at IO.write (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/streams.js:80:16)                                                                                             
    at Socket.ondata (_stream_readable.js:556:20)                                                      
    at emitOne (events.js:96:13)                                                                       
    at Socket.emit (events.js:188:7)                                                                   
    at readableAddChunk (_stream_readable.js:177:18)                                                   
    at Socket.Readable.push (_stream_readable.js:135:10)                                               
    at TCP.onread (net.js:542:20)                                                                      
                                                     
```

**Comment by DerekTBrown** [comment]
```
   Error: Cannot read property 'roles' of null
    at /home/derekbro/Projects/tuxlab-app/node_modules/gagarin/lib/meteor/methods.js:105:17            
    at DDPClient._message (/home/derekbro/Projects/tuxlab-app/node_modules/ddp/lib/ddp-client.js:144:7)
    at .<anonymous> (/home/derekbro/Projects/tuxlab-app/node_modules/ddp/lib/ddp-client.js:84:10)      
    at emitOne (events.js:96:13)                                                                       
    at emit (events.js:188:7)                                                                          
    at EventTarget.dispatchEvent (/home/derekbro/Projects/tuxlab-app/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)                                                                
    at instance._receiveMessage (/home/derekbro/Projects/tuxlab-app/node_modules/faye-websocket/lib/faye/websocket/api.js:123:10)                                                                             
    at .<anonymous> (/home/derekbro/Projects/tuxlab-app/node_modules/faye-websocket/lib/faye/websocket/api.js:41:49)                                                                                          
    at emitOne (events.js:101:20)                                                                      
    at emit (events.js:188:7)                                                                          
    at .<anonymous> (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)                                                                                    
    at pipe (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)                                                                                                
    at Pipeline._loop (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)                                                                                       
    at Pipeline.processIncomingMessage (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)                                                                      
    at instance.processIncomingMessage (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)                                                              
    at instance._emitMessage (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)                                                                           
    at instance._emitFrame (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)                                                                             
    at instance.parse (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:141:18)                                                                                  
    at instance.parse (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/driver/client.js:62:58)                                                                                 
    at IO.write (/home/derekbro/Projects/tuxlab-app/node_modules/websocket-driver/lib/websocket/streams.js:80:16)                                                                                             
    at Socket.ondata (_stream_readable.js:556:20)                                                      
    at emitOne (events.js:96:13)                                                                       
    at Socket.emit (events.js:188:7)                                                                   
    at readableAddChunk (_stream_readable.js:177:18)                                                   
    at Socket.Readable.push (_stream_readable.js:135:10)                                               
    at TCP.onread (net.js:542:20)                                                                                                         
```
